GET http://localhost:8000/member/member/count
Accept: application/json


<> 2023-09-01T104318.200.json
###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=17713088
###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile":"13000000000"
}



###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "17713088352",
  "code": "8888"
}