
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "name":"test4",
  "idCard": "123321231",
  "type": "1"
}

###

GET http://localhost:8001/member/passenger/query-list?page=1&size=3
Content-Type: application/json
token:{{token}}
